services:
  nginx:
    image: nginx/nginx-njs-acme
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    hostname: home.steinkamp.us
    environment:
      - NJS_ACME_SERVER_NAMES=steinkamp.us home.steinkamp.us plugins.steinkamp.us musics.steinkamp.us photos.steinkamp.us esstraba.steinkamp.us ships.steinkamp.us
      - NJS_ACME_DIRECTORY_URI=https://acme-v02.api.letsencrypt.org/directory
      - NJS_ACME_ACCOUNT_EMAIL=zack@steinkamp.us
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./dropbox:/usr/share/nginx/html/dropbox
      - njs_acme:/etc/nginx/njs-acme
volumes:
  njs_acme:
