version: '3'
services:
  nginx:
    image: nginxinc/nginx-njs-acme
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    hostname: home.steinkamp.us
    environment:
      - NJS_ACME_SERVER_NAMES=steinkamp.us home.steinkamp.us photos.steinkamp.us
      - NJS_ACME_DIRECTORY_URI=https://acme-v02.api.letsencrypt.org/directory
      - NJS_ACME_ACCOUNT_EMAIL=zack@steinkamp.us
    healthcheck:
      test: ["CMD", "curl", "-f", "http://home.steinkamp.us/acme/auto"]
      interval: 1m30s
      timeout: 90s
      retries: 3
      start_period: 10s
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - njs_acme:/etc/nginx/njs-acme
volumes:
  njs_acme:
